version: '3.8'
services:
  api:
    build: ./backend/
    restart: unless-stopped
    command: flask run --host 0.0.0.0
    depends_on:
      - db-mongo
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env.prod
    volumes:
      - apidata:/app
    networks:
      - frontend
      - backend

  db-mongo:
    image: mongo
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_DATABASE: todo
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: MngDb321
    volumes:
      - ./backend/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
  backend:

volumes:
  mongodbdata:
  apidata: